### ISSUE TITLE
Validate parameters in body

### ISSUE THREAD

**Issue by nicolastrres** [pipermerriam/flex#49] opened 2015-02-02 20:17 UTC
Is there a way to validate parameters in the body?, if I have for example the following schema:
```ssh
post:
      description: Creates a new pet in the store.  Duplicates are allowed
      operationId: addPet
      parameters:
        - name: pet
          in: body
          description: Pet to add to the store
          required: true
          schema:
            $ref: '#/definitions/NewPet'
```
Here is the link of the example I am using: https://github.com/swagger-api/swagger-spec/blob/master/examples/v2.0/yaml/petstore-expanded.yaml 
There is a way to validate that the parameters received in the body of the post are right?
I saw in the documentation that this is not explicit so I think that maybe this feature don't exist.

**Comment by pipermerriam** [comment] 2015-02-02 20:26
`body` and `formData` are not yet implemented.

https://github.com/pipermerriam/flex/blob/master/flex/validation/operation.py#L94

Getting those in is high on my priority list, but finishing https://github.com/pipermerriam/flex/pull/42 is my first priority.

**Comment by nicolastrres** [comment] 2015-02-02 20:30
Great!
Thanks for the quick response @pipermerriam

**Comment by pipermerriam** [comment] 2015-02-05 03:56
closing as this is a duplicate of #9

**Closed by pipermerriam** 2015-02-05 03:56 UTC
